### ISSUE TITLE
poll return 404 when `require 'message_bus'` in config/unicorn.rb

### ISSUE THREAD

**Issue by jstdoit** [discourse/message_bus#136]
As mentioned in `README.md`, I added `after_fork` in `config/unicorn.rb`, then the browser's poll got `404` error.

```ruby
# After forking, restore your ActiveRecord connection.
require 'message_bus'
after_fork do |server, worker|
	defined?(ActiveRecord::Base) && ActiveRecord::Base.establish_connection
	MessageBus.after_fork
end
```

But, when I removed `require 'message_bus'`, it works well, so I suppose it is the `require 'message_bus'` that caused the problem.

After some struggle, I cannot find the reason, is there anyone who met the same pro?

**Comment by jstdoit** [comment]
![image](https://cloud.githubusercontent.com/assets/1089041/24578365/de861902-1711-11e7-80fa-41b5cecb3665.png)

**Comment by SamSaffron** [comment]
what is in your Gemfile? Are you not doing `require: false` with message_bus?

**Comment by jstdoit** [comment]
@SamSaffron No, i didn't.

**Comment by feliperaul** [comment]
@SamSaffron I'm having the exact same problem and my config/unicorn is exactly the same as @jstdoit 

Locally, everything works fines and I see real time updates on the subscribed channel on the browser.

After the first test deploy, I could only see updates after a large number of seconds (I guess it's after the specified time in ms the long poll resets). 

I then read the README.rd where it stated `Forking/threading app servers
If you're using a forking or threading app server and you're not getting immediate updates from published messages, you might need to reconnect Redis/PostgreSQL in your app server config:`, and that was exactly my use case, so I went ahead and modified unicorn.rb, but now I get 404 on every request:

![image](https://user-images.githubusercontent.com/743879/35100967-e880fa26-fc44-11e7-8159-70eb13d94fd5.png)

**Comment by feliperaul** [comment]
This is my complete unicorn-production.rb config file:

```
worker_processes 24

app_directory = '/home/[app_name]/www'

working_directory "#{app_directory}/current"

listen "unix:#{app_directory}/shared/tmp/sockets/unicorn-production.sock", :backlog => 2048

timeout 60

preload_app true

pid "#{app_directory}/shared/tmp/pids/unicorn-production.pid"

stderr_path "#{app_directory}/shared/log/unicorn-production.stderr.log"
stdout_path "#{app_directory}/shared/log/unicorn-production.stdout.log"

if GC.respond_to?(:copy_on_write_friendly=)
  GC.copy_on_write_friendly = true
end

before_exec do |server|
  ENV["BUNDLE_GEMFILE"] = "./Gemfile"
end

before_fork do |server, worker|
  old_pid = "#{app_directory}/shared/tmp/pids/unicorn-production.pid.oldbin"
  if File.exists?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
  # the following is recomended for Rails + "preload_app true"
  # as there's no need for the master process to hold a connection
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection.disconnect!
  end
end

require 'message_bus'

after_fork do |server, worker|
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.establish_connection
  end
  MessageBus.after_fork
end

```

**Comment by SamSaffron** [comment]
Is this a subdirectory setup? how does `rake middleware` look?
