### ISSUE TITLE
Unable to configure and use baseurl in rails application

### ISSUE THREAD

**Issue by ff-parasp** [discourse/message_bus#202]
Hello,
I have configured baseurl in my application js file like.
 `
   MessageBus.baseUrl = 'fa/';
    MessageBus.start();
    MessageBus.subscribe("/notification_channel_" + window.wsConfig.sessionId, function(data){
        console.log(data);
    }
`
I keep getting following error in my Rails application
`ActionController::RoutingError` (No route matches [POST] `"/fa/message-bus/fc1684579dd54b9bb0a89fd8e4a3fa5d/poll.`

I tried exploring lib/message_bus/rack/middleware.rb file but could not find any code handling response with custom baseurl. Please help. Thanks

**Comment by SamSaffron** [comment]
well we use PATH_INFO so I am guessing you need to configure your app so Rack is aware of the subfolder and uses SCRIPT_NAME as `your_subfolder` 

I did see some discussion here: https://github.com/rails/rails/issues/24393
