### ISSUE TITLE
Why docs state that alwaysLongPoll true should only be used for debugging? Or why we use simple polling in background?

### ISSUE THREAD

**Issue by feliperaul** [discourse/message_bus#207]
Let's say you're building a chat app (Slack clone), that triggers a `new Notification` when a new message arrives.

With the default MessageBus js configuration, messages do arrive instantaneously when tabs are in foreground, but take up to 60 seconds to arrive when tab is not focused due to lib falling back to a regular polling strategy (instead of long polling), because it polls using `backgroundCallbackInterval` which defaults to `60000`.

I know the lib is smart enough to immediately start a new long poll as soon as the browser tab comes to focus, which has the effect of immediately displaying the new data, but it doesn't fix the issue of needing that data in realtime in the background tabs for the browser notification to happen in a timely fashion. 

One way to change this behavior would be to change `alwaysLongPoll` to `true`, which works fine in my tests, but documentation states that this should be used for debugging only.

So:

1. The reason to fallback to regular polling in background tabs is just to avoid hitting the server every 25 seconds (the value of `long_polling_interval` in `message_bus.rb`), using a more relaxed 60 seconds default?

2. If that's the case, would you welcome a pull request that updates documentation explaining this reasoning and removes the indication that `alwaysLongPoll` should be used for debugging purposes only?

Last but not least, I'd like just to point out that since `long_polling_interval` is currently hardcoded in `message_bus.rb` to 25 seconds, setting the backgroundCallbackInterval to anything < `25000` will post to the server more often in the background tabs than if one just used long polling, right?

**Comment by SamSaffron** [comment]
Yeah this is a tricky problem, I think if you have the bandwidth and really need all the background tabs to always get notifications there are 2 options

1. Use the always long poll stuff

2. Better still, wire up a service worker to do the polling and distribute stuff to the various tabs 

I am fine to update the documentation here. Also would love to see an example service worker client.

Regarding winding back to long poll more aggressively than 25 seconds, yeah that is probably not ideal.

**Comment by feliperaul** [comment]
@SamSaffron Sam, I want to share how I solved this.

There are some libs that provide tab election and tab messaging functionality. 

I chose https://github.com/dabblewriter/tab-election for this task.

You can then do something like this.

On every page:

```
import { waitForLeadership } from 'tab-election';


const tabBroadcaster = waitForLeadership(() => {

  MessageBus.alwaysLongPoll = true;

  MessageBus.start();
  
  MessageBus.subscribe("/chatrooms", (data) => {
    tabBroadcaster.postMessage('chatroomMessage', data);
  });

});
```

Then, anywhere else (for example, in my chat Vue.js beforeMount hook):

```

tabBroadcaster.on('chatroomMessage', (json) => { // json.data is the payload }

```

So the subscription is only active at one single tab at a time, which connects to the server. As soon as that tab is closed, another one picks up (you can use `document.title = "I'm Leader"` inside the waitForLeadership callback to easily see the tabs electing a new leader.

Lastly, when that leader receives a payload from MessageBus, it posts to all other tabs, which have subscribed via the `.on('chatroomMessage')` hook. 

It's working in production.
