### ISSUE TITLE
Channel backlog size

### ISSUE THREAD

**Issue by tobymao** [discourse/message_bus#221]
I'd like to have different backlog sizes for specific channels.

/a = 100
/b = 1

Is this possible? It seems like you can only set a global channel backlog size.

**Comment by SamSaffron** [comment]
Yes, on publish you can specify the size of the channel. 

```
MessageBus.publish("/b", "test", max_backlog_size: 1)

**Comment by tobymao** [comment]
thanks! 

haha, no this is for my personal project 

https://18xx.games
https://github.com/tobymao/18xx

**Comment by SamSaffron** [comment]
:) good luck, 

If you notice any areas of the readme that need help PR totally welcome.
