### ISSUE TITLE
Authentication/Authorisation

### ISSUE THREAD

**Issue by vitobotta** [discourse/message_bus#224]
Hi! I am looking to replace ActionCable with MessageBus, but I am confused as to how I can authenticate and authorise who can receive a message. Do I use client_ids or user_ids? Sorry I read the README but I am still confused.

With ActionCable, I know who the user is and accept or reject the subscription to the channel depending on permissions. So the client can't get the stream of messages if they don't have the permissions. I don't need to keep or lookup a list of user IDs for this.

How can I achieve something similar with MessageBus?

Thanks in advance!

**Comment by vitobotta** [comment]
Nevermind, I got it working with user_ids. I wonder how efficient this is though with many users?

**Comment by SamSaffron** [comment]
MessageBus is extremely efficient with enormous amounts of users, at Discourse we have forums with millions of users. 

user_ids and group_ids is the way to go. See: https://github.com/discourse/discourse/blob/0cbaa8d813f8cf911f48a44d95f596428b89b55e/config/initializers/004-message_bus.rb for an example initializer

**Comment by vitobotta** [comment]
That sounds more scalable than ActionCable :D It was very quick and easy to replace it with MessageBus for what I do. Thanks!

**Comment by SamSaffron** [comment]
awesome @vitobotta, how is it all working? As expected?

**Comment by vitobotta** [comment]
Hi @SamSaffron, sorry for the delay. Yeah it's working pretty well, thanks! :)

I'm using it to send some UI updates to clients with background jobs. With ActionCable I had a problem where web sockets connections are cut by Nginx when Nginx has to reload its configuration. My app allows users to add custom domains, so each time a custom domain is added, Nginx has to reload its configuration causing problems to web sockets. I experimented with separate Nginx ingress controllers for normal http traffic and ws (I am on Kubernetes), and that seems to work to some extent but MessageBus is easier. Because of the polling and that the messages are in a backlog so you can receive them even after a disconnection, it seems to be working better for what I do. Thanks! :)

**Comment by SamSaffron** [comment]
Thanks heaps for getting back to me, so happy it is working well for you!
