### ISSUE TITLE
Failed to process job: can't modify frozen String

### ISSUE THREAD

**Issue by tobymao** [discourse/message_bus#227]
Running on docker, ruby 2.7, postgres 12.2, unicorn, roda, sequel.

rack_1     | W, [2020-06-01T14:02:23.485044 #1272]  WARN -- : Failed to process job: can't modify frozen String: "" ["/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus/message.rb:23:in `encode'", "/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus/backends/postgres.rb:280:in `publish'", "/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus.rb:370:in `publish'", "/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus.rb:714:in `block in new_subscriber_thread'", "/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus/timer_thread.rb:110:in `do_work'", "/usr/local/bundle/gems/message_bus-3.3.0/lib/message_bus/timer_thread.rb:38:in `block in initialize'"]

**Comment by SamSaffron** [comment]
@jeremyevans this one sure is confusing

https://github.com/discourse/message_bus/blob/d65fbca73053625afb38eba937a0a3505f8dca32/lib/message_bus/message.rb#L23-L23

```
# frozen_string_literal: true

p 1.to_s.frozen?

p "1".to_i.to_s << "X" << "Y"
```

This all passes just fine for me on local on 2.7.1 and 2.7.0 

I can see the to_i being called here: 

https://github.com/discourse/message_bus/blob/d65fbca73053625afb38eba937a0a3505f8dca32/lib/message_bus/backends/postgres.rb#L54-L54

Any idea what this could be? 

@tobymao have you tested on 2.7.1?

**Comment by jeremyevans** [comment]
The only thing I can think of is a library is being used that memoizes the Integer#to_s call and returns a frozen string.

**Comment by tobymao** [comment]
@SamSaffron yea sorry, this is on 2.7.1, I have not tested 2.7.0. would it change performance to create strings rather than mutate them?

**Comment by SamSaffron** [comment]
I think @jeremyevans is on to something here, what does your Gemfile and Gemfile.lock look like? 

When you run a console to your app what does `2.to_s.frozen?` return?

**Comment by SamSaffron** [comment]
> would it change performance to create strings rather than mutate them?

only one way to answer ... we should bench it :)

**Comment by tobymao** [comment]
`# frozen_string_literal: true

source 'https://rubygems.org'

gem 'argon2'
gem 'c_lexer'
gem 'mailjet'
gem 'message_bus'
gem 'mini_racer'
gem 'opal'
gem 'rake'
gem 'require_all'
gem 'roda'
gem 'sequel'
gem 'sequel-pg_advisory_lock'
gem 'sequel_pg'
gem 'snabberb'
gem 'tilt'
gem 'uglifier'
gem 'unicorn'
gem 'unicorn-worker-killer'

group :development do
  gem 'pry-byebug'
  gem 'rerun'
  gem 'rubocop'
  gem 'sequel-annotate'
end

group :test do
  gem 'rspec'
end
`

`GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.0.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    argon2 (2.0.2)
      ffi (~> 1.9)
      ffi-compiler (>= 0.1)
    ast (2.4.0)
    byebug (11.1.3)
    c_lexer (2.6.4.1.1)
      ast (~> 2.4.0)
      parser (= 2.6.4.1)
    coderay (1.1.2)
    concurrent-ruby (1.1.6)
    diff-lcs (1.3)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    execjs (2.7.0)
    ffi (1.12.2)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    get_process_mem (0.2.5)
      ffi (~> 1.0)
    http-accept (1.7.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    jaro_winkler (1.5.4)
    kgio (2.11.3)
    libv8 (7.3.492.27.1)
    listen (3.2.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mailjet (1.5.4)
      activesupport (>= 3.1.0)
      rack (>= 1.4.0)
      rest-client
    message_bus (3.3.0)
      rack (>= 1.1.3)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2020.0512)
    mini_racer (0.2.14)
      libv8 (> 7.3)
    minitest (5.14.1)
    netrc (0.11.0)
    opal (1.0.3)
      ast (>= 2.3.0)
      parser (~> 2.6)
    parallel (1.19.1)
    parser (2.6.4.1)
      ast (~> 2.4.0)
    pg (1.2.3)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.9.0)
      byebug (~> 11.0)
      pry (~> 0.13.0)
    rack (2.2.2)
    rainbow (3.0.0)
    raindrops (0.19.1)
    rake (13.0.1)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    require_all (3.0.0)
    rerun (0.13.0)
      listen (~> 3.0)
    rest-client (2.1.0)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    roda (3.32.0)
      rack
    rspec (3.9.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
    rspec-core (3.9.2)
      rspec-support (~> 3.9.3)
    rspec-expectations (3.9.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-support (3.9.3)
    rubocop (0.78.0)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.6)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.7)
    ruby-progressbar (1.10.1)
    sequel (5.32.0)
    sequel-annotate (1.5.0)
      sequel (>= 4)
    sequel-pg_advisory_lock (0.1.2)
      sequel
    sequel_pg (1.13.0)
      pg (>= 0.18.0, != 1.2.0)
      sequel (>= 4.38.0)
    snabberb (0.4.2)
      opal (~> 1.0)
    thread_safe (0.3.6)
    tilt (2.0.10)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.7)
    unicode-display_width (1.6.1)
    unicorn (5.5.5)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    unicorn-worker-killer (0.4.4)
      get_process_mem (~> 0)
      unicorn (>= 4, < 6)
    zeitwerk (2.3.0)

PLATFORMS
  ruby

DEPENDENCIES
  argon2
  c_lexer
  mailjet
  message_bus
  mini_racer
  opal
  pry-byebug
  rake
  require_all
  rerun
  roda
  rspec
  rubocop
  sequel
  sequel-annotate
  sequel-pg_advisory_lock
  sequel_pg
  snabberb
  tilt
  uglifier
  unicorn
  unicorn-worker-killer

BUNDLED WITH
   2.1.4
`

**Comment by tobymao** [comment]
[gems.txt](https://github.com/discourse/message_bus/files/4727189/gems.txt)

**Comment by tobymao** [comment]
`docker-compose exec rack rake prod_irb
/usr/local/bin/irb -r ./models
irb(main):001:0> require_relative 'api'
=> true
irb(main):002:0> 0.to_s.frozen?
=> false
irb(main):003:0> 1.to_s.frozen?
=> false
irb(main):004:0> 2.to_s.frozen?
=> false
`

**Comment by SamSaffron** [comment]
@tobymao can you confirm my fix fixes it, turns out changing the implementation made it a touch faster so I went ahead and changed it.

**Comment by tobymao** [comment]
using diff --git a/Gemfile b/Gemfile
index aaa459d..5f3fda6 100644
--- a/Gemfile
+++ b/Gemfile
@@ -5,7 +5,7 @@ source 'https://rubygems.org'
 gem 'argon2'
 gem 'c_lexer'
 gem 'mailjet'
-gem 'message_bus'
+gem 'message_bus', :git => 'https://github.com/discourse/message_bus.git'
 gem 'mini_racer'
 gem 'opal'
 gem 'rake'
diff --git a/Gemfile.lock b/Gemfile.lock
index d61df42..93844f6 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,3 +1,10 @@
+GIT
+  remote: https://github.com/discourse/message_bus.git
+  revision: 81bb59499e221d1f6b71e04263cd56ae8138e7c0
+  specs:
+    message_bus (3.3.1)
+      rack (>= 1.1.3)
+

i don't see any errors in the logs thanks
