### ISSUE TITLE
user_ids and nil vs []

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [discourse/message_bus#232]
Hi, thanks for the great gem.

I've been experimenting with authentication using user_ids for sending private messages and I came across this line in the documentation: 
> Passing nil or [] to either client_ids, user_ids or group_ids is equivalent to allowing all values on each option.

However, my testing seems to indicate that while nil does that, [] sends the message to nobody. For what it's worth, I think this is the correct behaviour, as this could be quite a common use case:

`user_ids: User.users_who_can_access.pluck(:id)` 

Which, according the documentation I think would send to everybody if the scope returned new users, which I think is unexpected (and dangerous) behaviour.

Thanks

**Comment by SamSaffron** [comment]
We did make this change earlier this year that is related: 

https://github.com/discourse/message_bus/blob/81bb59499e221d1f6b71e04263cd56ae8138e7c0/CHANGELOG#L32-L32

I think the documentation is correct though according to: 

https://github.com/discourse/message_bus/blob/81bb59499e221d1f6b71e04263cd56ae8138e7c0/lib/message_bus/client.rb#L137-L148

The empty array behavior can be desirable in some cases where you are publishing either to specific user or groups.

**Comment by tom-acceleratecompliance** [comment]
Hi Sam,
Thanks for the comment, that makes sense.
Just to confirm, intended behaviour now / in future, (my testing is on 2.1.5) that this:

`MessageBus.publish('/test', user_ids: []) `

would send the message to all users?

**Comment by SamSaffron** [comment]
Yeah ... though I am open to stopping this in the outset.

Maybe we should amend it so we raise during publish if you attempt to publish to an empty group list or empty user list. 

The behavior can be a bit surprising and you should not attempt to publish stuff to nobody.

cc @tgxworld

**Comment by tom-acceleratecompliance** [comment]
Yeah that makes a lot of sense, thanks for the update.
Absolutely understand it's just my use-case, but I use a huge amount of this type of code:

```
MessageBus.publish('/test', user_ids: users_in_group(permissions_group).pluck(:id))
```

There are rare occurrences where nobody is assigned to that permissions group, so if you proceed with that I'll need to go through and update to something like:

```
ids = users_in_group(permissions_group).pluck(:id)
MessageBus.publish('/test', user_ids: ids) if ids.any?
```

Which is fine, but it feels like it would be something that is easy to miss with potentially very serious consequences for missing it. When in doubt. sending to nobody might give you a bug, but sending to everybody might give you a security incident.


Thanks for hearing me out!

**Comment by SamSaffron** [comment]
Sure, I made this change which is technically breaking, but I agree that in the long term it is better


https://github.com/discourse/message_bus/commit/fe340adeadd3f7a5966ca882bd1eba7263e1c4b4
