### ISSUE TITLE
How does MessageBus avoid hitting a connection limit on the backend? 

### ISSUE THREAD

**Issue by yoobles** [discourse/message_bus#233]
It seems like from what I'm reading in the source (at least for redis) that MessageBus creates a new backend connection for every subscription. Am I misunderstanding this or does MessageBus implement any kind of pooling or multiplexing so that it wouldn't be a connection per subscription?

**Comment by SamSaffron** [comment]
We certainly multiplex, have a look at message_bus.rb, it is not the
responsibility of the backed, if it were we would have to multiplex on
every backend repeating work

**Comment by yoobles** [comment]
Thanks for the response, I was typing out my analysis as you responded!

From what I can tell, MessageBus creates a new thread for every browser that connects. These thread lambdas are stored as part of the overall subscriptions hash/dict and separated by site and then channel. 

The underlying redis backend must be creating a pubsub connection for each channel that's requested. I can't find the code for this but it has to be the case. Then when the redis subscriber receives a new message, it passes the message through to all of the threads who then pass it to the browser. 

Permissions via user_id are accomplished before the thread sends the message over to the browser by comparing the user_ids at initialization with the message user_ids.

Thus you're multiplexing one redis channel connection across multiple users but still sending all messages over to all thread subscribers and then handling permissions at the MessageBus level. 

Does this sound like a reasonable analysis of MessageBus?

**Comment by SamSaffron** [comment]
> From what I can tell, MessageBus creates a new thread for every browser that connects. 

This is certainly not the case. We would scale quite poorly if that was the case.

**Comment by yoobles** [comment]
Thanks for the clarification. I see now that `global_subscribe` listens to all "channels" which would eliminate the need to have a thread listening per actual redis channel.
