### ISSUE TITLE
alwaysLongPoll not working in Chrome

### ISSUE THREAD

**Issue by kylekyle** [discourse/message_bus#238]
The Javascript MessageBus client will not receive messages on a hidden Chrome tab. When you switch to the tab, all the messages arrive at once. I've tried a few things, but it should be as simple as this, right?

```javascript
MessageBus.alwaysLongPoll = true
```

Running Chrome 86.0.4240.75 on a Macbook.

**Comment by SamSaffron** [comment]
Yeah that is it, this is by design, we do it to save on bandwidth

**Comment by kylekyle** [comment]
Makes sense. In that case, you might consider removing the `alwaysLongPoll` code from the Javascript client code and from the README, which still advertises the option: 

Setting|Default|Info
----|---|---|
alwaysLongPoll|false|For debugging you may want to disable the "is browser in background" check and always long-poll

For what it's worth, I think it is a valuable option to keep. For instance, I would like to make a tab blink when there are new notifications (like Facebook Messenger does), but I can't actually receive messages unless the tab is active.

**Comment by SamSaffron** [comment]
Messages still arrive, just slower

When we stop long polling we still continue short polling, the assumption
is that you put the tab in the background cause you care less and can wait
a minute

**Comment by kylekyle** [comment]
What is the short poll period? It doesn't seem effected by the `backgroundCallbackInterval` parameter. I've waited a few minutes, but messages still don't arrive until the tab has focus ...

**Comment by SamSaffron** [comment]
see: https://github.com/discourse/message_bus/blob/master/assets/message-bus.js#L86 

Is this missing from the README?

**Comment by kylekyle** [comment]
Right, I did try that but it didn't seem to have any effect. No messages are received when the tab is hidden no matter the combination of options I set in the Javascript client AFAIKT.
