### ISSUE TITLE
npm package is out of date

### ISSUE THREAD

**Issue by benlangfeld** [discourse/message_bus#242]
The latest release of the npm package containing the JS client code is 3.3.0.

Is this package a first class citizen in the message_bus release process? I see it was created in https://github.com/discourse/message_bus/commit/e5ec7a969bb81dfff6f4b84bf2019bfd91886d2f but it doesn't seem to have caught on as newer releases have been cut.

**Comment by SamSaffron** [comment]
@eviltrout I am a very extremely embarrassed here, I never did an NPM release before and am afraid of messing it up. 

Any chance you can do a new release and add a tiny section somewhere in the readme of maybe DEV.md about how the release process to NPM works? (also add me to the list ... I am not sure if I am or not an NPM package owner)

**Comment by eviltrout** [comment]
I've bumped the version and added DEV.md with instructions on how to publish it. (It's very easy.) I double checked and you are a collaborator.

https://github.com/discourse/message_bus/commit/a357a852351cd518955fc2f0f0a35e005fd37f30

**Comment by benlangfeld** [comment]
I think we should merge https://github.com/discourse/message_bus/pull/247, cut 3.3.5 and yank the 3.3.4 npm package. See https://github.com/discourse/message_bus/commit/a357a852351cd518955fc2f0f0a35e005fd37f30#commitcomment-50075043

**Comment by eviltrout** [comment]
@SamSaffron is going to have to sort that out - I haven't been following this - I just cut a release like he asked.

**Comment by SamSaffron** [comment]
I sorted this out @benlangfeld just published 3.3.5 (both client and gem) 

Note, not yanking, I think we are going to need a very very strong argument to ever do so.

**Comment by SamSaffron** [comment]
Thanks @eviltrout ! I am off to the races now, also made sure I have 2fa on npm for extra safety.
