### ISSUE TITLE
CORS preflight caching impossible

### ISSUE THREAD

**Issue by benlangfeld** [discourse/message_bus#245]
Since the message_bus JS client [passes `cache: false` to $.ajax](https://github.com/discourse/message_bus/blob/master/assets/message-bus.js#L228), an incrementing query parameter is added to the URL, which prevents a browser from utilising the CORS preflight cache.

The jQuery documentation states:

> If set to false, it will force requested pages not to be cached by the browser. Note: Setting cache to false will only work correctly with HEAD and GET requests. It works by appending "_={timestamp}" to the GET parameters. The parameter is not needed for other types of requests, except in IE8 when a POST is made to a URL that has already been requested by a GET.

The message_bus middleware implementation [sets the correct headers to prevent the browser caching the actual response](https://github.com/discourse/message_bus/blob/master/lib/message_bus/rack/middleware.rb#L115-L118) so it is unclear to me why it is necessary for the JavaScript client to also force a cache miss in a way that doubles request throughput in a use-case which requires CORS.

Is there any reason to keep passing `cache: false`?

**Comment by SamSaffron** [comment]
Oh maybe this is a misunderstanding I had we are making POST requests and have not made GET requests for so many years (maybe initial versions of MB had them) 

Sure, remove the cache: false.

**Comment by benlangfeld** [comment]
Thanks @SamSaffron , fixed in #246
