### ISSUE TITLE
Suggestions for moving to a new backend

### ISSUE THREAD

**Issue by ramontayag** [discourse/message_bus#310]
I'm considering moving to a new backend to have less moving parts (i.e. just use PG instead of Redis since I already have PG for the app's db).

How do you suggest a migration be executed? I think we would at least need to keep track of the last `message_id` and the last `global_id` so that when clients reconnect they don't keep sending their big ids which we'll take a while to reach.

**Comment by SamSaffron** [comment]
Howdy @ramontayag  my general suggestion would be to avoid migration and simply blow away the old data and start from scratch.

A migration is going to be very complicated and error prone, require many practice runs. The client already knows how to automatically recover from a flush.
