### ISSUE TITLE
Stuck understanding message_bus

### ISSUE THREAD

**Issue by arrowcircle** [discourse/message_bus#326]
Hey! I am trying to understand how to implement simple channels with updates based on message_bus with access control.

One thing I understood is I can send something like this to send per channel update:

```ruby
MessageBus.publish "/updates", "hello", channel_ids: ["XXX"]
```
But I cant understand how to make channel_id lookup method to check Authorization. I can reinvent auth logic in message bus initializer, but is there are better way not duplicating logic in rails?

I am thinking about providing something like JWT token to the client and decoding it in lookup method, but maybe there are better ways to implement auth and auth?

**Comment by benlangfeld** [comment]
https://github.com/discourse/message_bus#targeted-messages

**Comment by arrowcircle** [comment]
@benlangfeld thanks, I read this, but this does not help me to understand how to implement auth and auth.

**Comment by benlangfeld** [comment]
If you use cookie-based sessions, you can just look those up in the MB lookup callbacks and you're done.

Do you have a more specific question or problem you're encountering?
